# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  #config.vm.box = "precise64"
  #config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.box = "saucy-server-cloudimg-amd64-vagrant-disk1"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
  end
  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  # config.vm.network :hostonly, "192.168.33.10"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as another
  # physical device on your network.
  # config.vm.network :bridged

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.ssh.forward_agent = true
  #config.ssh.private_key_path = "~/.ssh/id_rsa"
  # For using ssh forwarding you have to set up your system
  # https://help.github.com/articles/using-ssh-agent-forwarding
  config.vm.hostname = "p2psafety.dev"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  #bind ssh to different port not to clash with other vms
  config.vm.network :forwarded_port, guest: 22, host: 2220, id: "ssh", auto_correct: true

  #
  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

  #hack for OSX
  if (/darwin/ =~ RUBY_PLATFORM) != nil
      config.vm.synced_folder "../", "/home/vagrant/p2psafety", type: "nfs", nfs_version:3
      config.nfs.map_uid = Process.uid
      config.nfs.map_gid = Process.gid
  else
      config.vm.synced_folder "../", "/home/vagrant/p2psafety", type: "nfs", nfs_version:4
  end


  # Enable provisioning with Puppet stand alone. 
  #
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "p2psafety.pp"
    puppet.facter = {
      "FACTER_uid" => "#{config.nfs.map_uid}",
      "FACTER_gid" => "#{config.nfs.map_gid}",
    }
  end
end
